apiVersion: v1
kind: Service
metadata:
  name: sit727-django-service
spec:
  type: NodePort
  selector:
    app: sit727-django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080